name: claymodel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-lock~=2.5.1
  - fiona~=1.9.5
  - geopandas-base~=0.14.1
  - h5netcdf~=1.3.0
  - jupyterlab~=4.0.7
  - jsonargparse~=4.27.0
  - lightning~=2.1.0
  - planetary-computer~=1.0.0
  - python=3.11
  - stackstac~=0.5.0
  - typeshed-client~=2.4.0
  - zarr~=2.16.1
