sentinel-2-l2a:
  band_order:
    - blue
    - green
    - red
    - rededge1
    - rededge2
    - rededge3
    - nir
    - nir08
    - swir16
    - swir22
  rgb_indices:
    - 2
    - 1
    - 0
  gsd: 10
  bands:
    mean:
      blue: 1109
      green: 1357
      red: 1554
      rededge1: 1888
      rededge2: 2419
      rededge3: 2626
      nir: 2739
      nir08: 2779
      swir16: 2377
      swir22: 1827
    std:
      blue: 1818
      green: 1766
      red: 1897
      rededge1: 1880
      rededge2: 1743
      rededge3: 1707
      nir: 1753
      nir08: 1659
      swir16: 1474
      swir22: 1381
    wavelength:
      blue: 0.493
      green: 0.56
      red: 0.665
      rededge1: 0.704
      rededge2: 0.74
      rededge3: 0.783
      nir: 0.842
      nir08: 0.865
      swir16: 1.61
      swir22: 2.19
landsat-c2l1:
  band_order:
    - red
    - green
    - blue
    - nir08
    - swir16
    - swir22
  rgb_indices:
    - 2
    - 1
    - 0
  gsd: 30
  bands:
    mean:
      red: 10685
      green: 10570
      blue: 11090
      nir08: 14805
      swir16: 12281
      swir22: 10116
    std:
      red: 6029
      green: 5416
      blue: 5473
      nir08: 6743
      swir16: 5894
      swir22: 4845
    wavelength:
      blue: 0.48
      green: 0.56
      red: 0.65
      nir08: 0.86
      swir16: 1.6
      swir22: 2.2
landsat-c2l2-sr:
  band_order:
    - red
    - green
    - blue
    - nir08
    - swir16
    - swir22
  rgb_indices:
    - 2
    - 1
    - 0
  gsd: 30
  bands:
    mean:
      red: 13672
      green: 13278
      blue: 12429
      nir08: 17790
      swir16: 14634
      swir22: 12717
    std:
      red: 9545
      green: 9372
      blue: 10107
      nir08: 8253
      swir16: 5305
      swir22: 4534
    wavelength:
      blue: 0.48
      green: 0.56
      red: 0.65
      nir08: 0.86
      swir16: 1.6
      swir22: 2.2
naip:
  band_order:
    - red
    - green
    - blue
    - nir
  rgb_indices:
    - 0
    - 1
    - 2
  gsd: 1.0
  bands:
    mean:
      red: 110.00
      green: 115.27
      blue: 98.01
      nir: 138.84
    std:
      red: 47.29
      green: 39.91
      blue: 35.52
      nir: 50.09
    wavelength:
      blue: 0.48
      green: 0.56
      red: 0.65
      nir: 0.842
linz:
  band_order:
    - red
    - green
    - blue
  rgb_indices:
    - 0
    - 1
    - 2
  gsd: 0.5
  bands:
    mean:
      red: 88.91
      green: 98.33
      blue: 88.53
    std:
      red: 42.64
      green: 38.12
      blue: 32.55
    wavelength:
      blue: 0.465
      green: 0.555
      red: 0.635
sentinel-1-rtc:
  band_order:
    - vv
    - vh
  gsd: 10
  bands:
    mean:
      vv: -203.36
      vh: -203.45
    std:
      vv: 2574.14
      vh: 2574.13
    wavelength:
      vv: 55465.76
      vh: 55465.76
