sentinel-2-l2a:
  band_order:
    - blue
    - green
    - red
    - rededge1
    - rededge2
    - rededge3
    - nir
    - nir08
    - swir16
    - swir22
  rgb_indices:
    - 2
    - 1
    - 0
  gsd: 10
  bands:
    mean:
      blue: 1200
      green: 1400
      red: 1500
      rededge1: 1800
      rededge2: 1900
      rededge3: 2000
      nir: 2200
      nir08: 2300
      swir16: 2400
      swir22: 2500
    std:
      blue: 200
      green: 250
      red: 300
      rededge1: 330
      rededge2: 340
      rededge3: 360
      nir: 400
      nir08: 420
      swir16: 450
      swir22: 480
    wavelength:
      blue: 0.49
      green: 0.56
      red: 0.665
      rededge1: 0.704
      rededge2: 0.74
      rededge3: 0.783
      nir: 0.842
      nir08: 0.865
      swir16: 1.61
      swir22: 2.19
landsat-c2l1:
  band_order:
    - red
    - green
    - blue
    - nir08
    - swir16
    - swir22
  rgb_indices:
    - 2
    - 1
    - 0
  gsd: 30
  bands:
    mean:
      blue: 1200
      green: 1400
      red: 1500
      nir08: 1800
      swir16: 1900
      swir22: 2000
    std:
      blue: 200
      green: 250
      red: 300
      nir08: 330
      swir16: 340
      swir22: 360
    wavelength:
      blue: 0.48
      green: 0.56
      red: 0.65
      nir08: 0.86
      swir16: 1.6
      swir22: 2.2
landsat-c2l2-sr:
  band_order:
    - red
    - green
    - blue
    - nir08
    - swir16
    - swir22
  rgb_indices:
    - 2
    - 1
    - 0
  gsd: 30
  bands:
    mean:
      blue: 1200
      green: 1400
      red: 1500
      nir08: 1800
      swir16: 1900
      swir22: 2000
    std:
      blue: 200
      green: 250
      red: 300
      nir08: 330
      swir16: 340
      swir22: 360
    wavelength:
      blue: 0.48
      green: 0.56
      red: 0.65
      nir08: 0.86
      swir16: 1.6
      swir22: 2.2
naip:
  band_order:
    - red
    - green
    - blue
    - nir
  rgb_indices:
    - 0
    - 1
    - 2
  gsd: 1.0
  bands:
    mean:
      red: 120
      green: 110
      blue: 100
      nir: 130
    std:
      red: 40
      green: 30
      blue: 20
      nir: 50
    wavelength:
      blue: 0.48
      green: 0.56
      red: 0.65
      nir: 0.842
linz:
  band_order:
    - red
    - green
    - blue
  rgb_indices:
    - 0
    - 1
    - 2
  gsd: 0.5
  bands:
    mean:
      blue: 100
      green: 100
      red: 100
    std:
      blue: 25
      green: 25
      red: 25
    wavelength:
      blue: 0.465
      green: 0.555
      red: 0.635
sentinel-1-rtc:
  band_order:
    - vv
    - vh
  gsd: 10
  bands:
    mean:
      vv: 100
      vh: 100
    std:
      vv: 25
      vh: 25
    wavelength:
      vv: 55465.76
      vh: 55465.76
