# lightning.pytorch==2.1.2
seed_everything: 42
data:
  metadata_path: configs/metadata.yaml
  batch_size: 6
  num_workers: 6
  train_chip_dir: /home/tam/Desktop/biomasters/train_cubes
  train_label_dir: /home/tam/Desktop/biomasters/train_agbm
  val_chip_dir: /home/tam/Desktop/biomasters/test_cubes
  val_label_dir: /home/tam/Desktop/biomasters/test_agbm
model:
  ckpt_path: checkpoints/clay-v1-base.ckpt
  lr: 1e-5
  wd: 0.05
  b1: 0.9
  b2: 0.95
  feature_maps:
    - 3
    - 5
    - 7
    - 11
trainer:
  accelerator: auto
  strategy: ddp
  devices: auto
  num_nodes: 1
  precision: 32-true
  log_every_n_steps: 5
  max_epochs: 20
  default_root_dir: checkpoints/regression
  fast_dev_run: False
  num_sanity_val_steps: 0
  limit_train_batches: 0.25
  limit_val_batches: 0.25
  accumulate_grad_batches: 6
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: developmentseed
        project: clay-regression
        log_model: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/regression
        auto_insert_metric_name: False
        filename: eurosat_epoch-{epoch:02d}_val-score-{val/score:.3f}
        monitor: val/score
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
