name: Deploy to GitHub Pages
on:
  push:
    branches: [master, nbdev]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: "pip"
        cache-dependency-path: settings.ini
    - name: Install Dependencies
      env:
        USE_PRE: ''
        TORCH_CPU: true
      shell: bash
      run: |
        set -ux
        python -m pip install --upgrade pip
        if [ $USE_PRE ]; then
          pip install -Uq git+https://github.com/fastai/ghapi.git
          pip install -Uq git+https://github.com/fastai/fastcore.git
          pip install -Uq git+https://github.com/fastai/execnb.git
          pip install -Uq git+https://github.com/fastai/nbdev.git
          wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
          sudo dpkg -i quarto*.deb
        else
          pip install -Uq nbdev
        fi
        if [ $TORCH_CPU ]; then
          test -f setup.py && pip install -e ".[dev]" --extra-index-url https://download.pytorch.org/whl/cpu
        else
          test -f setup.py && pip install -e ".[dev]"
        fi
        cd docs && nbdev_docs
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_docs/ # The folder the action should deploy.
